add ability to reset password from profile
germanStabile/target-MVD pull request #8
Opened 2018-11-21 15:51 UTC by germanStabile

![ezgif com-video-to-gif-6](https://user-images.githubusercontent.com/5719327/48852467-2ebad280-ed8c-11e8-952c-18506f5f8bd4.gif)

2018-11-21 19:31 UTC, mato2593 approved these changes

2018-11-22 14:44 UTC, xlasserre requested changes
👍 Only requested one change regarding a function that could be done in a simpler way

2018-11-22 14:44 UTC, missx commented on src/containers/EditAccountScreen/index.js
> +    }
You could have a togglePasswordModal function instead of having two and when setting state do ```this.setState({ showPasswordModal: !this.state.showPasswordModal });```

2018-11-22 16:02 UTC, peter7z approved these changes

2018-11-22 16:04 UTC, germanStabile commented on src/containers/EditAccountScreen/index.js
> +    }
will address on next PR

2018-11-22 16:04 UTC, merged